services:
  frontend:
    image: zotpluguci/zot_plug_frontend:beta
    container_name: zot_plug_frontend
    profiles: ["prod"]
    ports:
      - "3000:3000"
    environment:
      - BASE_URL=http://api:4000
    restart: unless-stopped

  broker:
    build: ./broker_mqtt
    container_name: broker_mqtt
    ports:
      - "1883:1883"
    depends_on:
      - postgres

  api:
    build:
      context: .
      dockerfile: rest_api/Dockerfile
    container_name: rest_api
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  cron:
    build: ./cron
    container_name: cron
    volumes:
      - ~/pg_db/backups:/backups
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    container_name: pg_db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - ~/pg_db/pgdata/:/var/lib/postgresql/data
      - ./pg_db/init.sql:/docker-entrypoint-initdb.d/init.sql
