version: '3.8'

services:
  broker:
    build: ./broker_mqtt
    container_name: broker_mqtt
    ports:
      - "1883:1883"
    depends_on:
      - postgres

  api:
    build: ./rest_api
    container_name: rest_api
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    container_name: pg_db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - ./pg_db/pgdata/:/var/lib/postgresql/data
